(()=>{
const functionData={
sum:{title:'SUM',question:'What is the total?',formula:'=SUM(A1:E1)',description:'SUM adds the numeric values in a range.',remember:'Use SUM when you want a total. It is usually easier to read than writing every plus sign yourself.',visual:`<div class="number-row"><span class="visual-cell">12</span><span class="visual-symbol">+</span><span class="visual-cell">8</span><span class="visual-symbol">+</span><span class="visual-cell">15</span><span class="visual-symbol">+</span><span class="visual-cell">6</span><span class="visual-symbol">+</span><span class="visual-cell">9</span><span class="visual-symbol">→</span><span class="visual-result">50</span></div>`},
average:{title:'AVERAGE',question:'What is the mean value?',formula:'=AVERAGE(B2:F2)',description:'AVERAGE adds the numeric values and divides by how many numeric values are in the range.',remember:'Think: total ÷ number of items.',visual:`<div><div class="number-row"><span class="visual-cell">10</span><span class="visual-cell">20</span><span class="visual-cell">30</span><span class="visual-cell">20</span><span class="visual-cell">20</span></div><div class="number-row" style="margin-top:14px"><span class="visual-cell highlight">100 total</span><span class="visual-symbol">÷</span><span class="visual-cell highlight">5 items</span><span class="visual-symbol">→</span><span class="visual-result">20</span></div></div>`},
max:{title:'MAX',question:'What is the largest value?',formula:'=MAX(B2:F2)',description:'MAX returns the largest numeric value in a range.',remember:'MAX identifies the highest numeric value; it does not add or average the values.',visual:`<div class="number-row"><span class="visual-cell">14</span><span class="visual-cell">9</span><span class="visual-cell highlight">26</span><span class="visual-cell">18</span><span class="visual-cell">11</span><span class="visual-symbol">→</span><span class="visual-result">26</span></div>`},
min:{title:'MIN',question:'What is the smallest value?',formula:'=MIN(B2:F2)',description:'MIN returns the smallest numeric value in a range.',remember:'Use MIN when you want the lowest value rather than a total or average.',visual:`<div class="number-row"><span class="visual-cell">14</span><span class="visual-cell highlight">9</span><span class="visual-cell">26</span><span class="visual-cell">18</span><span class="visual-cell">11</span><span class="visual-symbol">→</span><span class="visual-result">9</span></div>`},
count:{title:'COUNT',question:'How many numeric values are there?',formula:'=COUNT(A1:F1)',description:'COUNT counts cells that contain numeric values.',remember:'COUNT ignores text and blank cells.',visual:`<div class="number-row"><span class="visual-cell highlight">125</span><span class="visual-cell highlight">82</span><span class="visual-cell blue">Apple</span><span class="visual-cell blank">(blank)</span><span class="visual-cell highlight">97</span><span class="visual-cell blue">Pending</span><span class="visual-symbol">→</span><span class="visual-result">3</span></div>`},
counta:{title:'COUNTA',question:'How many cells contain something?',formula:'=COUNTA(A1:F1)',description:'COUNTA counts nonblank cells, including cells containing numbers or text.',remember:'Use COUNTA when you care whether a cell contains something, not whether that something is numeric.',visual:`<div class="number-row"><span class="visual-cell highlight">125</span><span class="visual-cell highlight">82</span><span class="visual-cell highlight">Apple</span><span class="visual-cell blank">(blank)</span><span class="visual-cell highlight">97</span><span class="visual-cell highlight">Pending</span><span class="visual-symbol">→</span><span class="visual-result">5</span></div>`}}
const tray=document.getElementById('functionTray'),backdrop=document.getElementById('trayBackdrop'),closeButton=document.getElementById('trayClose'),title=document.getElementById('trayTitle'),question=document.getElementById('trayQuestion'),formula=document.getElementById('trayFormula'),visual=document.getElementById('trayVisual'),description=document.getElementById('trayDescription'),remember=document.getElementById('trayRemember');let lastTrigger=null;
function openTray(key,trigger){const d=functionData[key];if(!d)return;lastTrigger=trigger||null;title.textContent=d.title;question.textContent=d.question;formula.textContent=d.formula;visual.innerHTML=d.visual;description.textContent=d.description;remember.textContent=d.remember;backdrop.hidden=false;tray.classList.add('open');tray.setAttribute('aria-hidden','false');document.body.classList.add('tray-open');setTimeout(()=>closeButton.focus(),0)}
function closeTray(){tray.classList.remove('open');tray.setAttribute('aria-hidden','true');document.body.classList.remove('tray-open');setTimeout(()=>{backdrop.hidden=true;if(lastTrigger)lastTrigger.focus()},220)}
document.querySelectorAll('[data-function]').forEach(b=>b.addEventListener('click',()=>openTray(b.dataset.function,b)));closeButton.addEventListener('click',closeTray);backdrop.addEventListener('click',closeTray);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&tray.classList.contains('open'))closeTray()});
})();
